In [83]:
import numpy as np

In [84]:
r = np.ones((5,1))
w = np.zeros(shape=(5,5))
w[0][1] = 1
w[1][0] = 0.5
w[1][4] = 0.5
w[2][1] = 0.5
w[2][4] = 0.5
w[3][1] = 0.5
w[3][4] = 0.5
w[4][1] = 0.33333
w[4][2] = 0.33333
w[4][3] = 0.33333

In [85]:
w_t = np.transpose(w)

In [86]:
w_t

array([[0.     , 0.5    , 0.     , 0.     , 0.     ],
       [1.     , 0.     , 0.5    , 0.5    , 0.33333],
       [0.     , 0.     , 0.     , 0.     , 0.33333],
       [0.     , 0.     , 0.     , 0.     , 0.33333],
       [0.     , 0.5    , 0.5    , 0.5    , 0.     ]])

In [87]:
r

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [88]:
r_next = np.matmul (w_t,r)
r_next

array([[0.5    ],
       [2.33333],
       [0.33333],
       [0.33333],
       [1.5    ]])

In [89]:
while (np.linalg.norm(r_next-r) > 0.001):
    r= np.matmul (w_t,r)
    r_next = np.matmul (w_t,r)
r

array([[0.90919582],
       [1.81786397],
       [0.4543733 ],
       [0.4543733 ],
       [1.36388172]])